/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewGameDialog.java
 *
 * Created on Jun 30, 2010, 6:03:20 PM
 */

package com.luugiathuy.games.reversi;

import java.awt.Frame;

/**
 *
 * @author Luu Gia Thuy
 */
public class NewGameDialog extends javax.swing.JDialog {

	/** */
	private static final long serialVersionUID = 2205120567519151731L;
	
	
	/** Creates new form NewGameDialog */
    public NewGameDialog(Frame frame, boolean modal) {
        super(frame, modal);
        initComponents();
        setLocationRelativeTo(frame);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnComputerFirst = new javax.swing.JCheckBox();
        btnStartGame = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Game");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnComputerFirst.setText("Computer first");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnComputerFirst, gridBagConstraints);

        btnStartGame.setText("Start Game");
        btnStartGame.setActionCommand("startgame");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnStartGame, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnCancel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
    	Reversi.getInstance().setIsCompTurn(btnComputerFirst.isSelected());
    	Reversi.getInstance().newGame();
    	this.setVisible(false);
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JCheckBox btnComputerFirst;
    private javax.swing.JButton btnStartGame;
    // End of variables declaration//GEN-END:variables

}
