/*
 * Reversi.java
 *
 * Created on Jun 17, 2010, 11:31:51 PM
 */

package com.luugiathuy.games.reversi;

import java.awt.BorderLayout;

import javax.swing.UIManager;

/**
 *
 * @author Luu Gia Thuy
 */
public class ReversiFrame extends javax.swing.JFrame {

    /**	 */
	private static final long serialVersionUID = -389310768365918217L;
	
	private ReversiPanel mReversiPanel;
	
	/** Creates new form Reversi */
    public ReversiFrame() {
        initComponents();
        
        // add reversi panel
        mReversiPanel = new ReversiPanel();
        this.add(mReversiPanel, BorderLayout.CENTER);
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: 	Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        gameMenu = new javax.swing.JMenu();
        mnuNewGame = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reversi");
        setResizable(false);

        gameMenu.setText("Game");

        mnuNewGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuNewGame.setText("New...");
        mnuNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewGameActionPerformed(evt);
            }
        });
        gameMenu.add(mnuNewGame);

        jMenuBar.add(gameMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewGameActionPerformed
    	NewGameDialog newGameDialog = new NewGameDialog(this, true);
    	newGameDialog.setVisible(true);
    }//GEN-LAST:event_mnuNewGameActionPerformed
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    	// set to user's look and feel
    	try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (Exception e) {
		}
		
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReversiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu gameMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem mnuNewGame;
    // End of variables declaration//GEN-END:variables

}
